---
deployment:
  tasks:
    - export DEPLOYPATH=/home/doctorloveskin/intranetapp.doctorloveskin.it/
#    - export DEPLOYPATH=/home/doctorloveskin/intranet.doctorloveskin.it/ 
    - /bin/cp -R * $DEPLOYPATH